### ISSUE TITLE
Images with get parameters not working

### ISSUE THREAD

**Issue by Zeyckler** [mdamien/chrome-extension-image-center#7]
You can try it adding some get param in the URL:
Example (works): http://cdni.wired.co.uk/1920x1280/g_j/GOOGLELOGO_1.jpg
Example (doesn't work): http://cdni.wired.co.uk/1920x1280/g_j/GOOGLELOGO_1.jpg?test=1

**Comment by mdamien** [comment]
thanks, I have the same problem with images without an 'image-like' extension in the url. This one should be fixed by simply adding to the regexes.

I had loading by content-type detection before but I was kind of buggy: https://github.com/mdamien/chrome-extension-image-center/commit/945b0a46e59341cd5d1235f171c7bf52d3cd6853
